"""
ArthMitra AI — Live Scheme Ingestion Pipeline
Curated dataset of 30+ verified Central & State government schemes.
Sources: NSP (scholarships.gov.in), MahaDBT, pmkisan.gov.in, pmjay.gov.in, etc.
Runs at startup and refreshes every 6 hours via asyncio background task.
"""
import json
import asyncio
from datetime import datetime
from database import SessionLocal, LiveScheme

# ─── CURATED SCHEME DATASET ──────────────────────────────────────────────────
# Each entry maps exactly to the LiveScheme DB model.
CURATED_SCHEMES = [
    # ── CENTRAL GOVERNMENT — AGRICULTURE ──
    {
        "scheme_name": "PM Kisan Samman Nidhi",
        "sponsoring_body": "Ministry of Agriculture & Farmers Welfare",
        "category": "Agriculture",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": "Farmer",
        "benefit_amount": "₹6,000/year (3 installments of ₹2,000)",
        "benefit_type": "DBT",
        "deadline": "Ongoing",
        "official_link": "https://pmkisan.gov.in/",
        "source_portal": "Central",
        "description": "Direct income support of ₹6,000/year to landholding farmer families in three equal installments directly into Aadhaar-linked bank accounts.",
        "required_docs": json.dumps(["aadhaar", "land_record", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Who is eligible?", "a": "All landholding farmers' families with cultivable land in their name."},
            {"q": "Are institutional landholders eligible?", "a": "No, institutional landholders are excluded."},
            {"q": "How long does verification take?", "a": "Typically 15–30 working days after submission and document verification."},
            {"q": "Where do I register?", "a": "Visit pmkisan.gov.in → 'New Farmer Registration' or your nearest Common Service Center (CSC)."},
        ]),
    },
    {
        "scheme_name": "PM Fasal Bima Yojana",
        "sponsoring_body": "Ministry of Agriculture & Farmers Welfare",
        "category": "Agriculture",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": "Farmer",
        "benefit_amount": "Crop loss compensation up to 80–90% of insured sum",
        "benefit_type": "Insurance",
        "deadline": "Season-based (Kharif: July 31, Rabi: Dec 31)",
        "official_link": "https://pmfby.gov.in/",
        "source_portal": "Central",
        "description": "Comprehensive crop insurance covering losses due to natural calamities, pests, and diseases. Premium as low as 1.5% for Rabi crops.",
        "required_docs": json.dumps(["aadhaar", "land_record", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What crops are covered?", "a": "All food crops, oilseeds, and annual commercial/horticultural crops."},
            {"q": "How do I claim?", "a": "Notify bank or insurance company within 72 hours of crop damage via the PMFBY portal or toll-free number 14447."},
        ]),
    },
    {
        "scheme_name": "Kisan Credit Card (KCC)",
        "sponsoring_body": "NABARD / Ministry of Agriculture",
        "category": "Agriculture",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": "Farmer",
        "benefit_amount": "Credit up to ₹3 Lakhs at 4% interest rate",
        "benefit_type": "Loan",
        "deadline": "Ongoing",
        "official_link": "https://www.nabard.org/content.aspx?id=463",
        "source_portal": "Central",
        "description": "Provides farmers with timely, adequate credit for crop cultivation, post-harvest expenses, and maintenance of farm assets at subsidised interest rates.",
        "required_docs": json.dumps(["aadhaar", "land_record", "bank_passbook", "income_cert"]),
        "faq_json": json.dumps([
            {"q": "What is the credit limit?", "a": "Up to ₹3 Lakhs at 4% effective annual interest (7% minus 3% subvention)."},
            {"q": "Where to apply?", "a": "Any nationalized bank, cooperative bank, or regional rural bank nearest to you."},
        ]),
    },
    # ── CENTRAL GOVERNMENT — HEALTH ──
    {
        "scheme_name": "Ayushman Bharat PM-JAY",
        "sponsoring_body": "National Health Authority, Ministry of Health",
        "category": "Health",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 300000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "₹5 Lakhs health cover per family per year",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://pmjay.gov.in/",
        "source_portal": "Central",
        "description": "World's largest health assurance scheme providing ₹5 Lakh/family/year for secondary and tertiary hospitalization at 25,000+ empanelled hospitals.",
        "required_docs": json.dumps(["aadhaar", "ration_card", "income_cert"]),
        "faq_json": json.dumps([
            {"q": "Is there any limit on family size?", "a": "No, there is no cap on family size or age of members."},
            {"q": "Which hospitals are covered?", "a": "All government hospitals and 25,000+ empanelled private hospitals. Find nearest at pmjay.gov.in."},
            {"q": "How long does card generation take?", "a": "The Ayushman Golden Card is generated immediately at the hospital/CSC upon biometric verification."},
            {"q": "Can I use it at private hospitals?", "a": "Yes, at all empanelled private hospitals. Verify at pmjay.gov.in/find-hospital."},
        ]),
    },
    {
        "scheme_name": "Janani Suraksha Yojana (JSY)",
        "sponsoring_body": "Ministry of Health & Family Welfare",
        "category": "Health",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "Female",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "₹1,400 (urban) or ₹1,000 (rural) per delivery",
        "benefit_type": "DBT",
        "deadline": "Ongoing",
        "official_link": "https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309",
        "source_portal": "Central",
        "description": "Promotes institutional delivery among BPL and Below-Poverty-Line pregnant women by providing cash incentives for safe deliveries in government hospitals.",
        "required_docs": json.dumps(["aadhaar", "ration_card", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Who is eligible?", "a": "All pregnant women who deliver in government or accredited private health facilities. BPL families receive higher incentives."},
        ]),
    },
    # ── CENTRAL GOVERNMENT — SOCIAL WELFARE ──
    {
        "scheme_name": "PM Ujjwala Yojana 2.0",
        "sponsoring_body": "Ministry of Petroleum & Natural Gas",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "SC,ST,OBC,EWS",
        "eligibility_income_max": 200000,
        "eligibility_education": None,
        "eligibility_gender": "Female",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "Free LPG connection + first refill + gas stove (₹1,600 support)",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://www.pmuy.gov.in/",
        "source_portal": "Central",
        "description": "Provides deposit-free LPG connections to women from economically weaker households for clean cooking fuel, safeguarding health of women and children.",
        "required_docs": json.dumps(["aadhaar", "ration_card", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Can men apply?", "a": "No, the LPG connection must be in the name of an adult woman of the household."},
            {"q": "Is caste certificate mandatory?", "a": "Yes, for applicants belonging to SC/ST/OBC categories."},
            {"q": "How to apply?", "a": "Visit pmuy.gov.in or your nearest LPG distributor (HP/Bharat/Indane Gas)."},
        ]),
    },
    {
        "scheme_name": "PM Awas Yojana – Gramin (PMAY-G)",
        "sponsoring_body": "Ministry of Rural Development",
        "category": "Housing",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 300000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "₹1.2 Lakhs (plain areas) / ₹1.3 Lakhs (hilly areas)",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://pmayg.nic.in/",
        "source_portal": "Central",
        "description": "Provides financial assistance to BPL rural households for construction of pucca (permanent) houses with basic amenities.",
        "required_docs": json.dumps(["aadhaar", "ration_card", "bank_passbook", "land_record"]),
        "faq_json": json.dumps([
            {"q": "Who is eligible?", "a": "Houseless families or those living in kutcha/dilapidated houses as per SECC 2011 data."},
            {"q": "How much time does it take?", "a": "Typically 12–18 months from application to first installment disbursement."},
        ]),
    },
    {
        "scheme_name": "National Social Assistance Programme (NSAP)",
        "sponsoring_body": "Ministry of Rural Development",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 200000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 60,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "₹200–₹500/month pension",
        "benefit_type": "DBT",
        "deadline": "Ongoing",
        "official_link": "https://nsap.nic.in/",
        "source_portal": "Central",
        "description": "Provides pension support to old-age persons, widows, and disabled citizens living below the poverty line through Indira Gandhi National Old Age Pension Scheme (IGNOAPS).",
        "required_docs": json.dumps(["aadhaar", "ration_card", "bank_passbook", "income_cert"]),
        "faq_json": json.dumps([
            {"q": "What are the components?", "a": "IGNOAPS (Old Age), IGNWPS (Widow), IGNDPS (Disability), NFBS (Family Benefit)."},
        ]),
    },
    # ── CENTRAL GOVERNMENT — EDUCATION / SCHOLARSHIPS ──
    {
        "scheme_name": "NSP Pre-Matric Scholarship for SC Students",
        "sponsoring_body": "Ministry of Social Justice & Empowerment",
        "category": "Education",
        "state": None,
        "eligibility_caste": "SC",
        "eligibility_income_max": 250000,
        "eligibility_education": "10th Pass",
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹3,500/year (hosteller) or ₹2,500/year (day scholar)",
        "benefit_type": "Scholarship",
        "deadline": "31-Oct (annual)",
        "official_link": "https://scholarships.gov.in/",
        "source_portal": "NSP",
        "description": "Pre-matric scholarships for SC students studying in Class 9 and 10 to prevent dropouts and encourage education.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Where to apply?", "a": "Register at scholarships.gov.in under 'Fresh Application' using Aadhaar and bank details."},
            {"q": "When is the deadline?", "a": "Usually October 31 each year. Check NSP portal for exact dates."},
            {"q": "How long to receive the amount?", "a": "3–4 months after submission and verification of all documents."},
        ]),
    },
    {
        "scheme_name": "NSP Post-Matric Scholarship for SC Students",
        "sponsoring_body": "Ministry of Social Justice & Empowerment",
        "category": "Education",
        "state": None,
        "eligibility_caste": "SC",
        "eligibility_income_max": 250000,
        "eligibility_education": "12th Pass",
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹25,000–₹1,25,000/year (course-dependent)",
        "benefit_type": "Scholarship",
        "deadline": "31-Oct (annual)",
        "official_link": "https://scholarships.gov.in/",
        "source_portal": "NSP",
        "description": "Financial assistance for SC students pursuing post-matric education (Class 11 onwards, including graduation and PG courses).",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Can engineering students apply?", "a": "Yes, second-year and above engineering students in government-recognized colleges can apply."},
            {"q": "Is renewal automatic?", "a": "No, you must renew annually on the NSP portal with updated marksheets and income certificate."},
        ]),
    },
    {
        "scheme_name": "NSP Post-Matric Scholarship for OBC Students",
        "sponsoring_body": "Ministry of Social Justice & Empowerment",
        "category": "Education",
        "state": None,
        "eligibility_caste": "OBC",
        "eligibility_income_max": 150000,
        "eligibility_education": "12th Pass",
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹12,000–₹1,25,000/year (course-dependent)",
        "benefit_type": "Scholarship",
        "deadline": "31-Oct (annual)",
        "official_link": "https://scholarships.gov.in/",
        "source_portal": "NSP",
        "description": "Financial assistance for OBC students pursuing post-matric education to reduce dropouts due to financial constraints.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What is the income limit?", "a": "Annual parental income must not exceed ₹1,50,000 (Rs. 1.5 Lakhs)."},
        ]),
    },
    {
        "scheme_name": "Central Sector Scholarship for College & University Students",
        "sponsoring_body": "Ministry of Education",
        "category": "Education",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 800000,
        "eligibility_education": "12th Pass",
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹12,000/year (UG) or ₹20,000/year (PG)",
        "benefit_type": "Scholarship",
        "deadline": "31-Oct (annual)",
        "official_link": "https://scholarships.gov.in/",
        "source_portal": "NSP",
        "description": "Merit-based scholarships for students scoring above 80th percentile in Class 12 board exams, pursuing regular degree courses.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What is the eligibility criterion?", "a": "Must have secured above the 80th percentile cutoff in Class 12 and be in the top 20% of successful candidates."},
        ]),
    },
    {
        "scheme_name": "Begum Hazrat Mahal National Scholarship (Maulana Azad)",
        "sponsoring_body": "Maulana Azad Education Foundation",
        "category": "Education",
        "state": None,
        "eligibility_caste": "SC,ST,OBC,EWS",
        "eligibility_income_max": 200000,
        "eligibility_education": "10th Pass",
        "eligibility_gender": "Female",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹5,000 (Class 9–10) or ₹6,000 (Class 11–12)",
        "benefit_type": "Scholarship",
        "deadline": "31-Oct (annual)",
        "official_link": "https://scholarships.gov.in/",
        "source_portal": "NSP",
        "description": "Scholarship for meritorious girl students belonging to minority communities (Muslim, Christian, Sikh, Buddhist, Parsi, Jain) to continue education.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Is it only for minority communities?", "a": "Yes, specifically for girls from Muslim, Christian, Sikh, Buddhist, Parsi, and Jain communities."},
        ]),
    },
    # ── MAHARASHTRA STATE — MahaDBT ──
    {
        "scheme_name": "MahaDBT – Dr. Panjabrao Deshmukh Vasatigruh Nirvah Bhatta",
        "sponsoring_body": "Social Justice Dept., Maharashtra",
        "category": "Education",
        "state": "Maharashtra",
        "eligibility_caste": "OBC",
        "eligibility_income_max": 800000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹800–₹2,000/month hostel maintenance allowance",
        "benefit_type": "Scholarship",
        "deadline": "30-Nov (annual)",
        "official_link": "https://mahadbt.maharashtra.gov.in/",
        "source_portal": "MahaDBT",
        "description": "Hostel & maintenance allowance for OBC students studying in Maharashtra who live away from home for education.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "How to apply on MahaDBT?", "a": "Register on mahadbt.maharashtra.gov.in → Select scheme → Fill profile → Upload documents → Submit."},
            {"q": "How long does verification take?", "a": "MahaDBT applications are processed within 45–60 days by the respective department."},
            {"q": "Can second-year engineering students apply?", "a": "Yes, students in any year of engineering enrolled in a government-recognized institution can apply."},
        ]),
    },
    {
        "scheme_name": "MahaDBT – Rajarshi Chhatrapati Shahu Maharaj Scholarship",
        "sponsoring_body": "Social Justice Dept., Maharashtra",
        "category": "Education",
        "state": "Maharashtra",
        "eligibility_caste": "OBC",
        "eligibility_income_max": 800000,
        "eligibility_education": "12th Pass",
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": "Student",
        "benefit_amount": "₹5,000–₹50,000/year (based on course and institution)",
        "benefit_type": "Scholarship",
        "deadline": "30-Nov (annual)",
        "official_link": "https://mahadbt.maharashtra.gov.in/",
        "source_portal": "MahaDBT",
        "description": "Scholarship for OBC students pursuing professional courses (Engineering, Medical, Law) in Maharashtra.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Is there an income limit?", "a": "Annual family income must not exceed ₹8,00,000 (Rs. 8 Lakhs) for OBC students."},
        ]),
    },
    {
        "scheme_name": "MahaDBT – Annasaheb Patil Loan Scheme (APMAVIMS)",
        "sponsoring_body": "APMAVIMS, Maharashtra",
        "category": "Social Welfare",
        "state": "Maharashtra",
        "eligibility_caste": "General",
        "eligibility_income_max": 800000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": 45,
        "eligibility_occupation": None,
        "benefit_amount": "Business loan guarantee up to ₹10 Lakhs at subsidised rate",
        "benefit_type": "Loan",
        "deadline": "Ongoing",
        "official_link": "https://mahadbt.maharashtra.gov.in/",
        "source_portal": "MahaDBT",
        "description": "Loan guarantee for economically backward General category youth of Maharashtra to start businesses.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Who is eligible?", "a": "General category (open caste) Maharashtra residents aged 18–45 with income below ₹8 Lakhs."},
        ]),
    },
    {
        "scheme_name": "Maharashtra Gharkul Yojana (SRA/PMAY Urban)",
        "sponsoring_body": "Housing Dept., Maharashtra",
        "category": "Housing",
        "state": "Maharashtra",
        "eligibility_caste": "ALL",
        "eligibility_income_max": 300000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "₹2.5 Lakhs subsidy under PMAY-U Credit Linked",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://mahadbt.maharashtra.gov.in/",
        "source_portal": "MahaDBT",
        "description": "Housing subsidy for SC/ST/OBC/EWS urban slum dwellers and rural poor in Maharashtra under the state's Gharkul Yojana.",
        "required_docs": json.dumps(["aadhaar", "income_cert", "caste_cert", "bank_passbook", "land_record"]),
        "faq_json": json.dumps([
            {"q": "Can existing homeowners apply?", "a": "No, only families without a pucca (permanent) house in their or spouse's name are eligible."},
        ]),
    },
    # ── WOMEN & CHILD WELFARE ──
    {
        "scheme_name": "Sukanya Samriddhi Yojana (SSY)",
        "sponsoring_body": "Ministry of Finance / India Post",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "Female",
        "eligibility_age_min": None,
        "eligibility_age_max": 10,
        "eligibility_occupation": None,
        "benefit_amount": "8.2% annual interest (tax-free maturity amount)",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://www.india.gov.in/sukanya-samriddhi-yojana",
        "source_portal": "Central",
        "description": "Long-term savings scheme for girl children up to age 10. Account matures in 21 years or at marriage after age 18 with tax-free returns at 8.2% p.a.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Who can open the account?", "a": "Parents or legal guardians of a girl child aged up to 10 years at any post office or authorized bank."},
            {"q": "What is the minimum deposit?", "a": "Minimum ₹250/year, maximum ₹1.5 Lakhs/year."},
        ]),
    },
    {
        "scheme_name": "Beti Bachao Beti Padhao",
        "sponsoring_body": "Ministry of Women & Child Development",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "Female",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "Access to gender-based support programs and scholarships",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://wcd.nic.in/bbbp-schemes",
        "source_portal": "Central",
        "description": "Addresses declining Child Sex Ratio (CSR) and promotes welfare and education of girl children through awareness campaigns and direct interventions.",
        "required_docs": json.dumps(["aadhaar"]),
        "faq_json": json.dumps([
            {"q": "What benefits does this scheme provide directly?", "a": "It acts as an umbrella program; actual financial benefits come through linked schemes like SSY, PMAY, and scholarships for girl students."},
        ]),
    },
    # ── EMPLOYMENT & SKILLS ──
    {
        "scheme_name": "PM SVANidhi – Street Vendor Micro-Credit",
        "sponsoring_body": "Ministry of Housing & Urban Affairs",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": "Street Vendor",
        "benefit_amount": "₹10,000 (1st), ₹20,000 (2nd), ₹50,000 (3rd) working capital loan",
        "benefit_type": "Loan",
        "deadline": "Ongoing",
        "official_link": "https://pmsvanidhi.mohua.gov.in/",
        "source_portal": "Central",
        "description": "Collateral-free working capital loans for street vendors to restart livelihoods post-COVID with digital payment incentives.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What is the interest rate?", "a": "Market rate, but with 7% interest subvention directly credited to beneficiary's bank account on timely repayment."},
        ]),
    },
    {
        "scheme_name": "PM Mudra Yojana (PMMY)",
        "sponsoring_body": "Ministry of Finance / SIDBI",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "Shishu: ₹50K | Kishore: ₹5L | Tarun: ₹10L collateral-free loan",
        "benefit_type": "Loan",
        "deadline": "Ongoing",
        "official_link": "https://www.mudra.org.in/",
        "source_portal": "Central",
        "description": "Provides loans up to ₹10 Lakhs to non-corporate small business/micro enterprises through banks, MFIs, and NBFCs without collateral.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook", "income_cert"]),
        "faq_json": json.dumps([
            {"q": "Is collateral required?", "a": "No collateral is required under PM Mudra Yojana for loans up to ₹10 Lakhs."},
            {"q": "Where to apply?", "a": "Any nationalized bank, NBFC, or MFI. Also apply online at mudra.org.in."},
        ]),
    },
    {
        "scheme_name": "PM Kaushal Vikas Yojana (PMKVY)",
        "sponsoring_body": "Ministry of Skill Development & Entrepreneurship",
        "category": "Education",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 15,
        "eligibility_age_max": 45,
        "eligibility_occupation": None,
        "benefit_amount": "Free skill training + ₹500/month stipend + certification",
        "benefit_type": "Scholarship",
        "deadline": "Ongoing",
        "official_link": "https://www.pmkvyofficial.org/",
        "source_portal": "Central",
        "description": "Free short-term skill development training for youth in 300+ job roles across 30+ sectors at PMKVY-empanelled training centers.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What courses are available?", "a": "300+ courses in IT, construction, retail, healthcare, agriculture, and more. Check pmkvyofficial.org for your nearest center."},
        ]),
    },
    {
        "scheme_name": "Mahatma Gandhi NREGA (MGNREGS)",
        "sponsoring_body": "Ministry of Rural Development",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "100 days guaranteed wage employment at state minimum wages",
        "benefit_type": "DBT",
        "deadline": "Ongoing",
        "official_link": "https://nrega.nic.in/",
        "source_portal": "Central",
        "description": "Guarantees 100 days of wage employment per financial year to any rural household whose adult members volunteer to do unskilled manual work.",
        "required_docs": json.dumps(["aadhaar", "ration_card", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "How to register?", "a": "Apply at your local Gram Panchayat office with Aadhaar, ration card, and bank details for a Job Card."},
            {"q": "What is the current wage rate?", "a": "Varies by state. Maharashtra NREGA wage is ₹238/day. Check nrega.nic.in for your state."},
        ]),
    },
    # ── PENSION & INSURANCE ──
    {
        "scheme_name": "Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM)",
        "sponsoring_body": "Ministry of Labour & Employment",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 180000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": 40,
        "eligibility_occupation": None,
        "benefit_amount": "₹3,000/month pension after age 60",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://maandhan.in/",
        "source_portal": "Central",
        "description": "Voluntary pension scheme for unorganized sector workers earning below ₹15,000/month. Government contributes equal amount to worker's contribution.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "What is my monthly contribution?", "a": "Ranges from ₹55/month (if you enroll at age 18) to ₹200/month (if you enroll at age 40). Government matches it."},
        ]),
    },
    {
        "scheme_name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "sponsoring_body": "Ministry of Finance / LIC",
        "category": "Health",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": 50,
        "eligibility_occupation": None,
        "benefit_amount": "₹2 Lakhs life cover at only ₹436/year premium",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://jansuraksha.gov.in/",
        "source_portal": "Central",
        "description": "Renewable 1-year life insurance cover of ₹2 Lakhs for death due to any reason at just ₹436/year via auto-debit from bank account.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "How to enroll?", "a": "Visit your bank branch or net banking portal. Provide consent for annual auto-debit of ₹436 from your savings account."},
        ]),
    },
    {
        "scheme_name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "sponsoring_body": "Ministry of Finance",
        "category": "Health",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": 70,
        "eligibility_occupation": None,
        "benefit_amount": "₹2 Lakhs (accidental death/disability) at ₹20/year",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://jansuraksha.gov.in/",
        "source_portal": "Central",
        "description": "Accident insurance scheme providing ₹2 Lakhs for accidental death or total permanent disability and ₹1 Lakh for partial permanent disability at just ₹20/year.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "How to enroll?", "a": "Through your bank branch or netbanking. Premium is auto-debited annually on June 1 each year."},
        ]),
    },
    # ── DIGITAL INDIA / OTHERS ──
    {
        "scheme_name": "PM Jan Dhan Yojana (PMJDY) – Zero Balance Account",
        "sponsoring_body": "Ministry of Finance",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 10,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "Zero-balance account + ₹2 Lakh accident cover + ₹30K overdraft",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://pmjdy.gov.in/",
        "source_portal": "Central",
        "description": "Financial inclusion scheme providing zero-balance savings accounts with RuPay debit card, accidental insurance, and overdraft facility.",
        "required_docs": json.dumps(["aadhaar"]),
        "faq_json": json.dumps([
            {"q": "What is the overdraft facility?", "a": "Account holders can avail up to ₹10,000 overdraft. Women account holders get up to ₹10,000 specifically."},
        ]),
    },
    {
        "scheme_name": "PM Garib Kalyan Anna Yojana (PMGKAY)",
        "sponsoring_body": "Ministry of Consumer Affairs, Food & Public Distribution",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": 200000,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": None,
        "eligibility_age_max": None,
        "eligibility_occupation": None,
        "benefit_amount": "5 kg free grain/person/month (wheat or rice)",
        "benefit_type": "Subsidy",
        "deadline": "Ongoing",
        "official_link": "https://dfpd.gov.in/",
        "source_portal": "Central",
        "description": "Provides 5 kg of free food grain per person per month to about 80 crore NFSA beneficiaries under the National Food Security Act.",
        "required_docs": json.dumps(["aadhaar", "ration_card"]),
        "faq_json": json.dumps([
            {"q": "Do I need a ration card?", "a": "Yes, beneficiaries must be listed in NFSA ration card. Link Aadhaar to ration card at your nearest PDS shop."},
        ]),
    },
    {
        "scheme_name": "Atal Pension Yojana (APY)",
        "sponsoring_body": "Ministry of Finance / PFRDA",
        "category": "Social Welfare",
        "state": None,
        "eligibility_caste": "ALL",
        "eligibility_income_max": None,
        "eligibility_education": None,
        "eligibility_gender": "ALL",
        "eligibility_age_min": 18,
        "eligibility_age_max": 40,
        "eligibility_occupation": None,
        "benefit_amount": "₹1,000–₹5,000/month guaranteed pension after age 60",
        "benefit_type": "Insurance",
        "deadline": "Ongoing",
        "official_link": "https://npscra.nsdl.co.in/nps-lite-apy.php",
        "source_portal": "Central",
        "description": "Guaranteed minimum pension scheme for unorganized sector workers. Choose pension amount (₹1K–₹5K/month) and contribute accordingly.",
        "required_docs": json.dumps(["aadhaar", "bank_passbook"]),
        "faq_json": json.dumps([
            {"q": "Can I exit before 60?", "a": "Premature exit is allowed only in case of terminal illness or death of the subscriber."},
        ]),
    },
]


async def run_ingestion():
    """Seeds/updates the LiveScheme table from the curated dataset. Safe to run multiple times."""
    db = SessionLocal()
    try:
        seeded_count = 0
        updated_count = 0
        for scheme_data in CURATED_SCHEMES:
            existing = db.query(LiveScheme).filter(
                LiveScheme.scheme_name == scheme_data["scheme_name"]
            ).first()

            if existing:
                # Update existing record fields
                for k, v in scheme_data.items():
                    setattr(existing, k, v)
                existing.last_synced = datetime.utcnow()
                updated_count += 1
            else:
                new_scheme = LiveScheme(**scheme_data, last_synced=datetime.utcnow(), is_active=True)
                db.add(new_scheme)
                seeded_count += 1

        db.commit()
        print(f"[Ingestion] ✅ Scheme sync complete: {seeded_count} new, {updated_count} updated. Total: {len(CURATED_SCHEMES)} schemes.")
    except Exception as e:
        db.rollback()
        print(f"[Ingestion] ❌ Error during scheme ingestion: {e}")
    finally:
        db.close()


async def ingestion_loop():
    """Runs ingestion at startup and then every 6 hours."""
    while True:
        await run_ingestion()
        # Sleep 6 hours between syncs
        await asyncio.sleep(6 * 3600)
